### ISSUE TITLE
Cannot import name 'makedev' from 'os'

### ISSUE THREAD

**Issue by EuphoricPenguin** [rapidrabbit76/SketchColorization#1]
```
(sketchcolorization) C:\Users\Mars\Documents\SketchColorization\app>fbs run
Traceback (most recent call last):
  File "C:\Users\Mars\Documents\SketchColorization\app\src\main\python\main.py", line 8, in <module>
    from view import Window
  File "C:\Users\Mars\Documents\SketchColorization\app\src\main\python\view\__init__.py", line 4, in <module>
    from .winodw import Window
  File "C:\Users\Mars\Documents\SketchColorization\app\src\main\python\view\winodw.py", line 3, in <module>
    from inference import predict
  File "C:\Users\Mars\Documents\SketchColorization\app\src\main\python\inference.py", line 3, in <module>
    from os import makedev, path
ImportError: cannot import name 'makedev' from 'os' (c:\users\mars\miniconda3\envs\sketchcolorization\lib\os.py)
```
I installed everything inside of a Python 3.7 conda environment, and I'm getting this particular output when I'm trying to run with fbs. Not sure what the issue is, but my hours of searching Google for answers were in vain.

**Comment by rapidrabbit76** [comment]
fbs was used for binary deployment 
how about changing the directory structure except fbs and running it directly with pyqt and python ?

Install Windows and we'll give you feedback again.

**Comment by EuphoricPenguin** [comment]
I'll see what I can do. This is already Windows?

**Comment by rapidrabbit76** [comment]
app development done on mac.

**Comment by EuphoricPenguin** [comment]
So, I'm re-visiting this again, and I'm honestly not sure what you mean by `running it directly with pyqt and python`. Would you mind explaining?

**Comment by rapidrabbit76** [comment]
@EuphoricPenguin  Thank you for the reply. 
I checked the error in Windows and fixed it.
I think it is an error that occurred because an unused module was imported.

please refer to the link for the modified [source code](https://github.com/rapidrabbit76/SketchColorization/releases/download/1.0.0/app_win_source.code.zip). (in releases, app_win_source.code.zip file)
in source code fbs has been removed, run it as `python main.py`
Copy the [SketchColorizationModel.onnx](https://github.com/rapidrabbit76/SketchColorization/releases/download/1.0.0/SketchColorizationModel.onnx) file into the app/src directory.

![win_01](https://user-images.githubusercontent.com/44311141/121474217-b7f38c80-c9fe-11eb-9aeb-8f5750192720.png)

![win_02](https://user-images.githubusercontent.com/44311141/121474231-bc1faa00-c9fe-11eb-845b-fe3753bde7b9.png)


`running it directly with pyqt and python` meaning was to remove the fbs element, modify the source code, and run it directly with pyqt. Sorry for not explaining in detail.

**Comment by EuphoricPenguin** [comment]
I figured it was more of a generalized push, but I'm unfortunately a bit of a foreigner when it comes to anything ML-related, and definitely Python as well. I'll check it out, and thank you for going out of your way to do this.

**Comment by EuphoricPenguin** [comment]
I finally got it working! Thank you for pointing this out to me. You don't know how long I've been messing with fiddly old source code bases of about what feels like 10 different projects to try and get anything running at all. I probably have like 30 hours or more over the past month or two perhaps. It means more than you'll ever know, so thank you.
Sincerely,
\- EuphoricPenguin
![working](https://user-images.githubusercontent.com/20228315/121830485-25b7e680-cc93-11eb-8a9c-cadfd2fdf874.png)
